### ISSUE TITLE
Unbounce Not Vulnerable

### ISSUE THREAD

**Issue by xElkomy** [Stratus-Security/Subdominator#1]
Unbounce Not Vulnerable

https://github.com/EdOverflow/can-i-take-over-xyz/issues/11

**Comment by coj337** [comment]
Unbounce is still vulnerable but it's a pretty rare edge case, I checked ~30 and only found one vulnerable takeover. If you're getting too much Unbounce spam you can ignore it with the --exclude-unlikely flag.
I believe the vulnerability happens when they point to a domain but never actually deploy anything to it or an account is deleted.
